import colors from 'tailwindcss/colors'
export default {
  content: [
    './app/**/*.{vue,js,ts}',
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}'
  ],
  theme: {
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    fontFamily: {
      sans: ['Inter', 'Arial', 'Graphik', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
    extend: {
      spacing: {
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      colors: { 
        theme: {
          bg: 'var(--bg)',
          elevated: 'var(--bg-elevated)',
          text: 'var(--text)',
          muted: 'var(--text-muted)',
          border: 'var(--border)',
          historyCardHoverBorder: 'var(--history-card-hover-border)',
          progressBarBg: 'var(--progressBar-bg)',
          card: 'var(--card)',
          cardMuted: 'var(--card-muted)',
          cardSoft: 'var(--card-soft)',
          panel: 'var(--panel)',
          surfaceLinkCard: 'var(--surface-link-card)',
          surfaceStaticCard: 'var(--surface-static-card)',
          surfaceIntroCard: 'var(--surface-intro-card)',
          surfaceResultsGlobalProfile: 'var(--surface-results-global-profile)',
          surfaceQuestionCard: 'var(--surface-question-card)',
          surfaceFormCard: 'var(--surface-form-card)',
          surfaceFormInput: 'var(--surface-form-input)',
          questionnaireInputBorder: 'var(--questionnaire-input-border)',
          formInputBorder: 'var(--form-input-border)',
          partnerFormInputBorder: 'var(--partner-form-input-border)',
          accent: 'var(--accent)',
          accentSoft: 'var(--accent-soft)',
          accentStrong: 'var(--accent-strong)',
          nav: 'var(--nav-bg)',
          navText: 'var(--nav-text)',
          navActive: 'var(--nav-active)',
          navDivider: 'var(--nav-divider)',
          button: 'var(--button-dark)',
          buttonText: 'var(--button-dark-text)',
          primary: 'var(--button-primary)',
          primaryText: 'var(--button-primary-text)',
          action: 'var(--button-rust)',
          actionText: 'var(--button-rust-text)',
          link: 'var(--link)',
          overlay: 'var(--overlay)',
          successBadgeBg: 'var(--success-badge-bg)',
          successBadgeText: 'var(--success-badge-text)',
          modalBg: 'var(--modal-bg)',
          modalText: 'var(--modal-text)',
          modalMuted: 'var(--modal-muted)',
          modalClose: 'var(--modal-close)',
          modalCloseHover: 'var(--modal-close-hover)',
          modalOverlay: 'var(--modal-overlay)',
          resultsSurface: 'var(--results-surface)',
          resultsSurfaceAlt: 'var(--results-surface-alt)',
          resultsSurfaceMuted: 'var(--results-surface-muted)',
          resultsOverlay: 'var(--results-overlay)',
          resultsSubprofileAnxietyBg: 'var(--results-subprofile-anxiety-bg)',
          resultsSubprofileAvoidanceBg: 'var(--results-subprofile-avoidance-bg)',
          resultsTriggerAnxietyBorder: 'var(--results-trigger-anxiety-border)',
          resultsTriggerAvoidanceBorder: 'var(--results-trigger-avoidance-border)',
          resultsTriggerHighText: 'var(--results-trigger-high-text)',
          resultsTriggerHighBg: 'var(--results-trigger-high-bg)',
          resultsTriggerMediumText: 'var(--results-trigger-medium-text)',
          resultsTriggerMediumBg: 'var(--results-trigger-medium-bg)',
          resultsTriggerLowText: 'var(--results-trigger-low-text)',
          resultsTriggerLowBg: 'var(--results-trigger-low-bg)',
        },
        primary: 'var(--surface-primary)',
        secondary: 'var(--surface-secondary)',
        lightBrown: 'var(--light-brown)',
        lightPeach: 'var(--bg)',
        rust : 'var(--accent)',
        brown: 'var(--button-dark)',
        softGreen: 'var(--card)',
        softPeach: 'var(--card-muted)',
        slateBlue: 'var(--surface-slate)',
      },
    }
  },
  variants: {
    extend: {
      borderColor: ['focus-visible'],
      opacity: ['disabled'],
    }
  },
  // plugins: [
  //   require('@tailwindcss/forms'),
  //   require('@tailwindcss/aspect-ratio'),
  //   require('@tailwindcss/typography'),
  //   require('tailwindcss-children'),
  // ],
}
